create table if not exists `artshows`(
    `id` int(11) not null auto_increment,
    `name` varchar(255) not null,
    `description` text not null,
    `image` varchar(255) not null,
    `artistID` int(11) not null,
    primary key(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `artshows` (`name`, `description`, `image`, `artistID`) VALUES 
    ('florealia','composizioni floreali','http://www.avant-gardeart.com/perrini/florealia/images/ff1_16t.jpg',1),
    ('antologica 1','tante cose belle del buon signor luigi pevini','http://www.avant-gardeart.com/perrini/antologica/images/vers2000.jpg',1),
    ('demoni','I Demoni dedicata a Fiodor Dostoevskij','http://www.avant-gardeart.com/perrini/demoni/images/vitelliu.jpg',1),
    ('antologica 2','non so cosa dire','http://www.avant-gardeart.com/perrini/antologica2/images/11_gif.jpg',1),
    ('icone 2005','opere religiose','http://www.avant-gardeart.com/perrini/icone2005/images/01_JPG.JPG',1);

create table if not exists `artpieces`(
    `id` int(11) not null auto_increment,
    `idArtShow` int(11) not null,
    `idArtist` int(11) not null,
    `title` varchar(255) not null,
    `year` varchar(15) not null,
    `dimensions` varchar(255) not null,
    `technics` text not null,
    `image` text not null,
    primary key(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `artpieces` (`idArtShow`, `idArtist`, `title`, `year`,`dimensions`, `technics`, `image`) VALUES
    (1,1,'Fantasia floreale 1/16T','2000','25 x 35 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff1_16t.jpg'),
    (1,1,'Fantasia floreale 10/16C','2000','30 x 40 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff10_16c.jpg'),
    (1,1,'Fantasia floreale 10/24T','1999','40 x 60 cm.','acrilico e tempera su tela/acrilic and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff10_24t.jpg'),
    (1,1,'Fantasia floreale 11/16C','2000','30 x 40 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff11_16c.jpg'),
    (1,1,'Fantasia floreale 11/24T','1999','50 x 60 cm.','olio e tempera su tela senza telaio/oil and watercolour on canvas without frame','http://www.avant-gardeart.com/perrini/florealia/images/ff11_24t.jpg'),
    (1,1,'Fantasia floreale 12/16C','2000','30 x 40 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff12_16c.jpg'),
    (1,1,'Fantasia floreale 12/24T','2000','40 x 60 cm.','acrilico e tempera su tela e carta/acrilic and watercolour on canvas and paper','http://www.avant-gardeart.com/perrini/florealia/images/ff12_24t.jpg'),
    (1,1,'Fantasia floreale 13/16C','2000','30 x 40 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff13_16c.jpg'),
    (1,1,'Fantasia floreale 13/24C','1999','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff13_24c.jpg'),
    (1,1,'Fantasia floreale 14/16C','2000','30 x 40 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff14_16c.jpg'),
    (1,1,'Fantasia floreale 14/24C','1999','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff14_24c.jpg'),
    (1,1,'Fantasia floreale 15/16C','2000','42 x 42 cm. ca.','olio e tempera su carta giapponese/oil and watercolour on japanese paper','http://www.avant-gardeart.com/perrini/florealia/images/ff15_16c.jpg'),
    (1,1,'Fantasia floreale 15/24C','1999','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff15_24c.jpg'),
    (1,1,'Fantasia floreale 16/16C','2000','42 x 42 cm. ca.','olio e tempera su carta giapponese/oil and watercolour on japanese paper','http://www.avant-gardeart.com/perrini/florealia/images/ff16_16c.jpg'),
    (1,1,'Fantasia floreale 16/24C','1999','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff16_24c.jpg'),
    (1,1,'Fantasia floreale 17/24C','1999','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff17_24c.jpg'),
    (1,1,'Fantasia floreale 18/24C','1999','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff18_24c.jpg'),
    (1,1,'Fantasia floreale 19/24C','1999','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff19_24c.jpg'),
    (1,1,'Fantasia floreale 2/16T','2000','25 x 35 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff2_16t.jpg'),
    (1,1,'Fantasia floreale 20/24C','2000','48,5 x 66 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff20_24c.jpg'),
    (1,1,'Fantasia floreale 21/24CV','2000','50 x 70 cm. ca.','olio e tempera su carta /oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff21_24c_v.jpg'),
    (1,1,'Fantasia floreale 22/24C','2000','48,5 x 66 cm. ca.','olio, tempera e smalto su carta/oil, watercolour and varnish on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff22_24c.jpg'),
    (1,1,'Fantasia floreale 23/24C','2000','48,5 x 66 cm. ca.','TM, olio, tempera e pastelli su carta/TM, oil, watercolour and pastels on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff23_24c.jpg'),
    (1,1,'Fantasia floreale 24/24T','1999','50 x 60 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff24_24t.jpg'),
    (1,1,'Fantasia floreale 3/16T','2000','25 x 35 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff3_16t.jpg'),
    (1,1,'Fantasia floreale 4/16T','2000','25 x 35 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff4_16t.jpg'),
    (1,1,'Fantasia floreale 4/24T','1999','50 x 60 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff4_24t.jpg'),
    (1,1,'Fantasia floreale 5/16T','2000','25 x 35 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff5_16t.jpg'),
    (1,1,'Fantasia floreale 5/24T','1999','50 x 60 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff5_24t.jpg'),
    (1,1,'Fantasia floreale 6/16T','2000','25 x 35 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff6_16t.jpg'),
    (1,1,'Fantasia floreale 6/24T','2000','40 x 60 cm.','olio, tempera e smalto su tela/oil, watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff6_24t.jpg'),
    (1,1,'Fantasia floreale 7/16T','2000','25 x 40 cm.','smalto, olio e tempera su tela/varnish, oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff7_16t.jpg'),
    (1,1,'Fantasia floreale 7/24T','1999','50 x 60 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff7_24t.jpg'),
    (1,1,'Fantasia floreale 8/16T','2000','25 x 40 cm.','smalto, olio e tempera su tela/varnish, oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff8_16t.jpg'),
    (1,1,'Fantasia floreale 8/24T','1999','50 x 60 cm.','olio e tempera su tela/oil and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff8_24t.jpg'),
    (1,1,'Fantasia floreale 9/16C','2000','30 x 40 cm. ca.','olio e tempera su carta/oil and watercolour on paper','http://www.avant-gardeart.com/perrini/florealia/images/ff9_16c.jpg'),
    (1,1,'Fantasia floreale 9/24T','2000','40 x 60 cm.','acrilico e tempera su tela/acrilic and watercolour on canvas','http://www.avant-gardeart.com/perrini/florealia/images/ff9_24t.jpg'),
    (2,1,'Verso il 2000','1994','30 x 40 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/vers2000.jpg'),
    (2,1,'L''uccello del malaugurio','1998','18 x 24 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/uccello.jpg'),
    (2,1,'Get off your slip','1997/1998','70 x 100 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/slip.jpg'),
    (2,1,'S. Andrea','1998','30 x 40 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/sandrea.jpg'),
    (2,1,'S. Anacleto','1998','30 x 40 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/sanacle.jpg'),
    (2,1,'Saggio','1998','18 x 24 cm.','olio, collage e T.M. su tela/oil, collage and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/saggio.jpg'),
    (2,1,'Senza titolo 24/05/N7','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/s2405N7.jpg'),
    (2,1,'Demone tribale','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/s2405N5.jpg'),
    (2,1,'Demone ancestrale','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/s2405N3.jpg'),
    (2,1,'Senza titolo 24/05/N28','1999/2000','30 x 40 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/s2405N28.jpg'),
    (2,1,'Il derby Roma-Lazio','1999','40 x 50 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/romala.jpg'),
    (2,1,'Demone Robotico','2000','45 x 55 cm.','olio, smalto e T.M. su tela/oil, varnish and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/robotico.jpg'),
    (2,1,'Ricciano','1992','100 x 150 cm.','olio, smalto e polimaterico su carta/oil, varnish and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica/images/ricciano.jpg'),
    (2,1,'Resurrezione','1996','60 x 80 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/resurrez.jpg'),
    (2,1,'La principessa Sissi','1998','35 x 45 cm.','olio e smalto su tela/oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica/images/principe.jpg'),
    (2,1,'Primitivo','1999','50 x 70 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/primitiv.jpg'),
    (2,1,'Allegra Preistoria','1994','90 x 120 cm.','olio e smalto fluorescente su tela di juta grezza/oil and fluorescent varnish on canvas of raw juta','http://www.avant-gardeart.com/perrini/antologica/images/preistor.jpg'),
    (2,1,'Pantaleone','1996','40 x 50 cm.','olio e T.M. su tela e carta intelata/oil and T.M. on canvas and canvas-paper','http://www.avant-gardeart.com/perrini/antologica/images/pantaleo.jpg'),
    (2,1,'Piazza del Popolo s.o./1','1999/2000','45 x 55 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/piazpopo.jpg'),
    (2,1,'Pesce subacqueo','1999/2000','30 x 40 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/pescesub.jpg'),
    (2,1,'Parsifal','1998/1999','70 x 100 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/parsifal.jpg'),
    (2,1,'Pan di zucchero','1993','60 x 80 cm.','olio, smalto e polimaterico su tela di juta grezza/oil, varnish and polimateric on canvas of raw juta','http://www.avant-gardeart.com/perrini/antologica/images/panzucch.jpg'),
    (2,1,'Nicolaus','1998','30 x 40 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/nicolaus.jpg'),
    (2,1,'Dedicato a Munch','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/munch.jpg'),
    (2,1,'Mucca','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/mucca.jpg'),
    (2,1,'La morte del re','1993','60 x 90 cm.','olio e smalto su sughero/oil and varnish on cork-oak','http://www.avant-gardeart.com/perrini/antologica/images/mortere.jpg'),
    (2,1,'Meduse','1996','40 x 50 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/meduse.jpg'),
    (2,1,'Maternità','1993','90 x 120 cm.','olio su tela di cotone grezza/oil on canvas of raw cotton','http://www.avant-gardeart.com/perrini/antologica/images/maternit.jpg'),
    (2,1,'Manitou','1996','30 x 40 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/manitou.jpg'),
    (2,1,'Lupo','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/lupo.jpg'),
    (2,1,'Lina','2000','35 x 50 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/lina.jpg'),
    (2,1,'Questa è Lilith','1994/1998','30 x 40 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/lilith.jpg'),
    (2,1,'Leone in agguato','1998','90 x 120 cm.','olio, smalto e T.M. su tela/oil, varnish and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/leone.jpg'),
    (2,1,'Discesa agli Inferi','1995/1996','90 x 120 cm.','olio e smalto su tela di juta grezza/oil and varnish on canvas of raw juta','http://www.avant-gardeart.com/perrini/antologica/images/inferi.jpg'),
    (2,1,'Grotte','1993','90 x 120 cm.','stucco e pigmento su tela di juta grezza/plaster and pigment on canvas of raw juta','http://www.avant-gardeart.com/perrini/antologica/images/grotte.jpg'),
    (2,1,'Grattacieli','1998','30 x 60 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/grattaci.jpg'),
    (2,1,'Buona giornata','1994','60 x 80 cm.','olio e smalto su tela/oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica/images/giornata.jpg'),
    (2,1,'Gioppino','1998/1999','60 x 80 cm.','olio e collage ad olio su tela/oil and collage of oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/gioppino.jpg'),
    (2,1,'Il generale della NATO','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/generale.jpg'),
    (2,1,'Fumetti','1996','6 tele/canvas 18 x 24 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/fumetti.jpg'),
    (2,1,'Florealità','1994','50 x 60 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/floreali.jpg'),
    (2,1,'Feticcio','1994','50 x 70 cm.','olio, smalto e T.M. su tela/oil, enamel and T.M on canvas','http://www.avant-gardeart.com/perrini/antologica/images/feticcio.jpg'),
    (2,1,'Fantasmi','1993','100 x 150 cm.','olio su carta/oil on paper','http://www.avant-gardeart.com/perrini/antologica/images/fantasmi.jpg'),
    (2,1,'Espressionismo lirico','1995','4 tele/canvas 40 x 50 cm.','olio su tela di juta grezza/oil on canvas of raw juta','http://www.avant-gardeart.com/perrini/antologica/images/espresli.jpg'),
    (2,1,'Enkidu','1997','50 x 60 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/enkidu.jpg'),
    (2,1,'Elettroshockabile','1991','50 x 60 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/elettros.jpg'),
    (2,1,'Divinità egizia','1998','18 x 24 cm.','olio, polimaterico e T.M. su tela/oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/divinit.jpg'),
    (2,1,'Depressione','1994','40 x 50 cm.','olio e T.M. su tela/oil and T.M. canvas','http://www.avant-gardeart.com/perrini/antologica/images/depressi.jpg'),
    (2,1,'Il croato','1998','18 x 24 cm.','olio e T.M. su tela/oil and T.M. canvas','http://www.avant-gardeart.com/perrini/antologica/images/croato.jpg'),
    (2,1,'Clown robotico','1997','55 x 65 cm.','olio, T.M. e polimaterico su carta Fabriano fuori produzione/oil, T.M. and polimatter on Fabriano paper out-production','http://www.avant-gardeart.com/perrini/antologica/images/clown.jpg'),
    (2,1,'Cleopatra','1997','35 x 45 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/cleopatr.jpg'),
    (2,1,'Ceffo','1993','40 x 50 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/ceffo.jpg'),
    (2,1,'Cavallo Pazzo','1995/1996','60 x 90 cm.','olio su sughero/oil on cork-oak','http://www.avant-gardeart.com/perrini/antologica/images/cavallop.jpg'),
    (2,1,'Bimbo triste','1993','cm. 55 x 75','olio e T.M. su carta intelata/oil and T.M. on canvas-paper','http://www.avant-gardeart.com/perrini/antologica/images/bimbo.jpg'),
    (2,1,'La bestia e la virtù','1993','90 x 120 cm.','olio su tela di cotone grezza/oil on canvas of raw cotton','http://www.avant-gardeart.com/perrini/antologica/images/bestiavi.jpg'),
    (2,1,'Benemerita','1994','70 x 100 cm.','smalto e tempera su cartone/varnish and gouache on cardboard','http://www.avant-gardeart.com/perrini/antologica/images/benemer.jpg'),
    (2,1,'Asterix','1999','60 x 80 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica/images/asterix.jpg'),
    (2,1,'La notte degli assassini','1994','30 x 40 cm.','olio e T.M. su tela/oil and T.M. canvas','http://www.avant-gardeart.com/perrini/antologica/images/assassin.jpg'),
    (2,1,'L''Architetto dell''Universo','1998','50 x 50 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/antologica/images/architet.jpg'),
    (2,1,'Apoteosi','1993','90 x 120 cm.','olio e smalto su tela di juta grezza/oil and varnish on canvas of raw juta','http://www.avant-gardeart.com/perrini/antologica/images/apoteosi.jpg'),
    (2,1,'Allegoria','1993','90 x 120 cm.','olio su tela di cotone grezza/oil on canvas of raw cotton','http://www.avant-gardeart.com/perrini/antologica/images/allegor.jpg'),
    (2,1,'L''Alfiere','1993','60 x 80 cm.','olio, smalto e T.M. su tela di iuta grezza/oil, enamel and T.M. on crude canvas of jute.','http://www.avant-gardeart.com/perrini/antologica/images/alfiere.jpg'),
    (2,1,'Alberi Solitari','1993','90 x 120 cm.','olio, smalto e polimaterico su tela di juta grezza/oil, varnish and polimateric on canvas of raw juta','http://www.avant-gardeart.com/perrini/antologica/images/alberiso.jpg'),
    (3,1,'Vitelius','1995','10 x 15 cm.','olio, smalto e polimaterico su cartone telato/oil, varnish and polimateric on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/vitelliu.jpg'),
    (3,1,'Strega','1999-2000','10 x 15 cm.','olio, smalto e polimaterico su tela/oil, varnish and polimateric on canvas','http://www.avant-gardeart.com/perrini/demoni/images/strega.jpg'),
    (3,1,'Sophia','1991-1992','30 x 40 cm.','olio, smalto e polimaterico su tela / oil, varnish and polimateric on canvas','http://www.avant-gardeart.com/perrini/demoni/images/sophia.jpg'),
    (3,1,'Sofisma (Piazza del Popolo)','2000','48 x 65 cm.','olio, smalto e polimaterico su carta/ oil, varnish and polimateric on paper','http://www.avant-gardeart.com/perrini/demoni/images/sofisma.jpg'),
    (3,1,'Primitività','1996-1997','60 x 75 cm.','olio, smalto e polimaterico su carta/ oil, varnish and polimateric on paper','http://www.avant-gardeart.com/perrini/demoni/images/primitiv.jpg'),
    (3,1,'Il pazzo del Deserto','1998','60 x 75 cm.','olio, smalto e polimaterico su carta/ oil, varnish and polimateric on paper','http://www.avant-gardeart.com/perrini/demoni/images/pazzdese.jpg'),
    (3,1,'Pandemonium','2000','24 x 32 cm.','acquarello su carta/ gouache on paper','http://www.avant-gardeart.com/perrini/demoni/images/pandemon.jpg'),
    (3,1,'Nicolaus','1998','30 x 40 cm.','olio, polimaterico e T.M. su tela / oil, polimateric and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/nicolaus.jpg'),
    (3,1,'M.P.P.M.','1994','13 x 18 cm.','olio, polimaterico e T.M. su vetro/ oil, polimateric and T.M. on glass','http://www.avant-gardeart.com/perrini/demoni/images/mppc.jpg'),
    (3,1,'La morte del Mandarino','1999','10 x 15 cm.','olio, polimaterico e T.M. su cartone telato/ oil, polimateric and T.M. on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/mortmand.jpg'),
    (3,1,'Demone Mortifero','1997','18 x 24 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/mortifer.jpg'),
    (3,1,'Monsieur La Mort','1999-2000','40 x 50 cm.','olio su tela / oil on canvas','http://www.avant-gardeart.com/perrini/demoni/images/monsieur.jpg'),
    (3,1,'Mongolico','1996','35 x 50 cm.','olio su tela / oil on canvas','http://www.avant-gardeart.com/perrini/demoni/images/mongolic.jpg'),
    (3,1,'Lupo','1997','18 x 24 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/lupo.jpg'),
    (3,1,'Luigi Filippo d''Orleans','1996','40 x 50 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/luigifil.jpg'),
    (3,1,'Lazio sei un demonio','1996','67 x 85 cm.','olio, tempera e smalto su carta / oil, gouache and varnish on paper','http://www.avant-gardeart.com/perrini/demoni/images/laziodem.jpg'),
    (3,1,'Jago','1996-1997','48 x 65 cm.','olio su carta / oil on paper','http://www.avant-gardeart.com/perrini/demoni/images/jago.jpg'),
    (3,1,'Demone Isteria','1995-1996','20 x 30 cm.','olio su tela/ oil on canvas','http://www.avant-gardeart.com/perrini/demoni/images/isterica.jpg'),
    (3,1,'Il cacciatore di Cappuccetto Rosso','1998','24 x 33 cm.','pastello e T.M. su carta / pastels and T.M. on paper','http://www.avant-gardeart.com/perrini/demoni/images/ilcaccia.jpg'),
    (3,1,'Il bastardino di Frà Diavolo','1998','10 x 15 cm.','olio, smalto e T.M. su cartone telato / oil, varnish and T.M. on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/ilbastar.jpg'),
    (3,1,'Fauno','1998-1999','13 x 18 cm.','olio e china su cartone telato / oil and ink on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/fauno.jpg'),
    (3,1,'Edipo e la Sfinge','1996','55 x 75 cm.','olio, smalto e polimaterico su carta/ oil, varnish and polimateric on paper','http://www.avant-gardeart.com/perrini/demoni/images/ediposfi.jpg'),
    (3,1,'Ecce Homo','2000','48 x 65 cm.','olio, smalto e polimaterico su carta / oil, varnish and polimateric on paper','http://www.avant-gardeart.com/perrini/demoni/images/eccehomo.jpg'),
    (3,1,'Deus ex machina','1994','13 x 18 cm.','olio, smalto e T.M. su cartone telato / oil, varnish and T.M. on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/deusexma.jpg'),
    (3,1,'Desiderio di concezione','1996','20 x 30 cm.','olio, china, polimaterico e T.M. su cartone telato / oil, ink, polimateric and T.M. on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/desiconc.jpg'),
    (3,1,'Demone Cosacco','1996','24 x 33 cm.','polimaterico e T.M. su carta / polimateric and T.M. on paper','http://www.avant-gardeart.com/perrini/demoni/images/demzar.jpg'),
    (3,1,'Demone vecchio','1996','10 x 15 cm.','smalto e T.M. su cartone telato /varnishl and T.M on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/demvecch.jpg'),
    (3,1,'Demone vampiro','1994','30 x 40 cm.','olio su tela / oil on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demvampi.jpg'),
    (3,1,'Demone Tribale','1997','18 x 24 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demtriba.jpg'),
    (3,1,'Demone Tasmania','1999','10 x 15 cm.','olio, polimaterico e T.M. su cartone telato/ oil, polimateric and T.M. on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/demtasma.jpg'),
    (3,1,'Demone Squalo','1996','20 x 30 cm.','olio, china, polimaterico e T.M. su cartone telato / oil, ink, polimateric and T.M. on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/demsqual.jpg'),
    (3,1,'Demone Sinoue','1996','10,5 x 13 cm.','olio e T.M. su tela di cotone / oil and T.M. on cotton canvas','http://www.avant-gardeart.com/perrini/demoni/images/demsinon.jpg'),
    (3,1,'Demone Seminole','1996','10,5 x 13 cm.','olio e T.M. su tela di cotone / oil and T.M. on cotton canvas','http://www.avant-gardeart.com/perrini/demoni/images/demsemin.jpg'),
    (3,1,'Demone scettico','1996','10 x 18 cm.','olio e T.M. su cartone / oil and T.M. on cardboard','http://www.avant-gardeart.com/perrini/demoni/images/demscett.jpg'),
    (3,1,'Demone Sannita','1996','24 x 33 cm.','polimaterico e T.M. su carta / polimateric and T.M. on paper','http://www.avant-gardeart.com/perrini/demoni/images/demsanni.jpg'),
    (3,1,'Demone Saladino','2000','10 x 15 cm.','olio e smalto su tela / oil and varnish on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demsalad.jpg'),
    (3,1,'Demone e quadratura del cerchio','1996','21 x 29,7 cm.','olio e T.M. su carta / oil T.M. on paper','http://www.avant-gardeart.com/perrini/demoni/images/demquadr.jpg'),
    (3,1,'Demone Pinocchio','1998','24 x 33 cm.','T.M. su carta / T.M. on paper','http://www.avant-gardeart.com/perrini/demoni/images/dempinoc.jpg'),
    (3,1,'Demone Pesce','1998','18 x 24 cm.','olio, smalto e T.M. su tela / oil, varnish and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/dempesce.jpg'),
    (3,1,'Demone marino','1995-1996','20 x 30 cm.','olio, smalto e T.M. su tela / oil, varnish and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demmarin.jpg'),
    (3,1,'Demone Legionario','1999','10 x 15 cm.','olio, smalto e polimaterico su cartone telato/oil, varnish and polimateric on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/demlegio.jpg'),
    (3,1,'Demone interlocutore','1997-98','10 x 15 cm.','T.M. su cartone telato/T.M. on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/deminter.jpg'),
    (3,1,'Demone Intellighenzia','1997','35 x 45 cm.','olio su tela/oil on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demintel.jpg'),
    (3,1,'Demone in fuga','1992','30 x 40 cm.','olio e smalto su cotone grezzo/oil and varnish on crude cotton','http://www.avant-gardeart.com/perrini/demoni/images/deminfug.jpg'),
    (3,1,'Demone idiota','1996','10 x 15 cm.','smalto e T.M. su cartone telato/varnish and T.M. on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/demidiot.jpg'),
    (3,1,'Demone Giocondo','1996-97','40 x 50 cm.','olio e smalto su tela di iuta/oil and varnish on iuta canvas','http://www.avant-gardeart.com/perrini/demoni/images/demgioco.jpg'),
    (3,1,'Demone Garibaldino','1999','10 x 15 cm.','olio e T.M. su cartone telato/oil and T.M on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/demgarib.jpg'),
    (3,1,'Demone Cayenna','1996','10,5 x 13 cm.','olio e T.M. su tela/oil and T.M on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demcogen.jpg'),
    (3,1,'Demone cieco','1991','40 x 50 cm.','olio, smalto e T.M. su tela e carta/oil, varnish and T.M on canvased paper','http://www.avant-gardeart.com/perrini/demoni/images/demcieco.jpg'),
    (3,1,'Demone ceffo','1999','10 x 15 cm.','smalto e T.M. su cartone telato/varnish and T.M on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/demceffo.jpg'),
    (3,1,'Demone capra-capretta','1995-96','10 x 15 cm.','smalto e T.M. su cartone telato/varnish and T.M on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/demcapra.jpg'),
    (3,1,'Demone Barbaro','1995-96','10 x 15 cm.','smalto e T.M. su cartone telato/varnish and T.M on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/dembarba.jpg'),
    (3,1,'Demone Argonauta','2000','45 x 55 cm.','olio, smalto e T.M. su tela/oil, varnish and T.M on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demargon.jpg'),
    (3,1,'Demone aracne','1996','10 x 15 cm.','smalto e T.M. su cartone telato/varnish and T.M on canvased boardcard','http://www.avant-gardeart.com/perrini/demoni/images/demaracn.jpg'),
    (3,1,'Demone ancestrale','1997','18 x 24 cm.','olio e T.M. su tela/oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/demoni/images/demances.jpg'),
    (3,1,'Demone agreste','1997','24 x 33 cm.','matita e T.M. su carta/pencil and T.M. on paper','http://www.avant-gardeart.com/perrini/demoni/images/demagres.jpg'),
    (3,1,'La Cometa di Halley','1998','13 x 18 cm.','olio e T.M. su cartone telato/oil and T.M. on canvased cardboard','http://www.avant-gardeart.com/perrini/demoni/images/cometaha.jpg'),
    (3,1,'Cane Pazzo','1995','75 x 100 cm.','smalto e T.M. su carta','http://www.avant-gardeart.com/perrini/demoni/images/canepazz.jpg'),
    (3,1,'Demone Bovalano','1996','10 x 15cm.','smalto e T.M. su cartone telato','http://www.avant-gardeart.com/perrini/demoni/images/bovalano.jpg'),
    (3,1,'Lucifero','1998-99','48 x 65 cm.','olio, pigmento, vernice, T.M. e polimaterico su carta/oil, pigments, varnishe, T.M and polimateric on paper','http://www.avant-gardeart.com/perrini/demoni/images/lucifero.jpg'),
    (4,1,'P.L. N°1','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/1_gif.jpg'),
    (4,1,'P.L. N°10','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/10_gif.jpg'),
    (4,1,'P.L. N°11','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/11_gif.jpg'),
    (4,1,'P.L. N°12','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/12_gif.jpg'),
    (4,1,'P.L. N°13','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/13_gif.jpg'),
    (4,1,'P.L. N°14','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/14_gif.jpg'),
    (4,1,'Nei meandri dell''inconscio','1993','70 x 100 cm.','Olio su tela/Oil on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/15_gif.jpg'),
    (4,1,'Uno sguardo dal cielo','1993-1994','50 x 70 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/16_gif.jpg'),
    (4,1,'P.L. N°17','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/17_gif.jpg'),
    (4,1,'Scoglio','1996','60 x 75 cm.','T.M. e smalto su carta/T.M. and varnish on paper','http://www.avant-gardeart.com/perrini/antologica2/images/18_gif.jpg'),
    (4,1,'Ariete','1996','50 x 70 cm.','T.M. e smalto su carta/T.M. and varnish on paper','http://www.avant-gardeart.com/perrini/antologica2/images/19_gif.jpg'),
    (4,1,'Mosè e il vitello d''oro','2000','20 x 25 cm.','Olioe smalto su cartone telato/Oil. and varnish on canvas paper','http://www.avant-gardeart.com/perrini/antologica2/images/2_gif.jpg'),
    (4,1,'P.L. N°20','1994-1995','50 x 70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/20_gif.jpg'),
    (4,1,'Zarathustra','1996','50 x 70 cm.','Olio e T.M. su carta/Oil and T.M. on paper','http://www.avant-gardeart.com/perrini/antologica2/images/21_gif.jpg'),
    (4,1,'Fiori pirotecnici','1996','50 x 70 cm.','Olio e T.M. su carta/Oil and T.M. on paper','http://www.avant-gardeart.com/perrini/antologica2/images/22_gif.jpg'),
    (4,1,'Figure allegoriche','1993','60 x 80 cm.','Olio su sughero/Oil on cork','http://www.avant-gardeart.com/perrini/antologica2/images/23_gif.jpg'),
    (4,1,'Bimbo','1994','20 x 30 cm.','Olio su tela/Oil on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/24_gif.jpg'),
    (4,1,'Diva anni ''60','1993-1994','30 x 40 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/25_gif.jpg'),
    (4,1,'Anima prigioniera','1994','50 x 70 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/26_gif.jpg'),
    (4,1,'Cuore trafitto','1994','20 x 30 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/27_gif.jpg'),
    (4,1,'Singa beer','1996-1997','50 x 60 cm.','Olio e pigmenti su tela/Oil and pigments on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/28_gif.jpg'),
    (4,1,'Meduse','1997-1998','40 x 50 cm.','Olio su tela/Oil on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/29_gif.jpg'),
    (4,1,'P.L. N°3','1994-1995','50 x 70 cm.','T.M. e smalto su carta/T.M. and varnish on paper','http://www.avant-gardeart.com/perrini/antologica2/images/3_gif.jpg'),
    (4,1,'Isteria','1992-1993','20 x 30 cm.','Olio su tela/Oil on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/30_gif.jpg'),
    (4,1,'Malinconia','1991-1992','30 x 40 cm.','Olio e polimaterico su tela/Oil and polimateric on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/31_gif.jpg'),
    (4,1,'Presepe','1996','70 x 100 cm.','Pastello su cartone/pastels on cardboard','http://www.avant-gardeart.com/perrini/antologica2/images/32_gif.jpg'),
    (4,1,'Rock and Roll','1994-1995','70 x 100 cm.','Gouache e T.M. su cartone/Gouache and T.M. on cardboard','http://www.avant-gardeart.com/perrini/antologica2/images/33_gif.jpg'),
    (4,1,'Metamorfosi','1993-1994','60 x80 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/34_gif.jpg'),
    (4,1,'Femina diabolica','1995','70 x100 cm.','Pastello e smalto su cartone/Pastels and varnish on cardboard','http://www.avant-gardeart.com/perrini/antologica2/images/35_gif.jpg'),
    (4,1,'Don Chisciotte e Sancho Panza','1996','70 x100 cm.','T.M. e smalto su cartone/T.M. and varnish on cardboard','http://www.avant-gardeart.com/perrini/antologica2/images/36_gif.jpg'),
    (4,1,'Per Tatiana','1994','90 x120 cm.','Olio e smalto su tela di cotone/Oil and varnish on cotton canvas','http://www.avant-gardeart.com/perrini/antologica2/images/37_gif.jpg'),
    (4,1,'Feticismo','1993','90 x120 cm.','Smalto e olio su tela di iuta/varnish and oil on iuta canvas','http://www.avant-gardeart.com/perrini/antologica2/images/38_gif.jpg'),
    (4,1,'P.L. N°39','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/39_gif.jpg'),
    (4,1,'P.L. N°4','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/4_gif.jpg'),
    (4,1,'P.L. N°40','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/40_gif.jpg'),
    (4,1,'P.L. N°41','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/41_gif.jpg'),
    (4,1,'P.L. N°42','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/42_gif.jpg'),
    (4,1,'P.L. N°43','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/43_gif.jpg'),
    (4,1,'P.L. N°44','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/44_gif.jpg'),
    (4,1,'P.L. N°45','1994-1995','50 x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric an paper','http://www.avant-gardeart.com/perrini/antologica2/images/45_gif.jpg'),
    (4,1,'Kore','2001','40 x50 cm.','Olio e smalto su cartone telato/Oil and varnish on canvased cardboard','http://www.avant-gardeart.com/perrini/antologica2/images/46_gif.jpg'),
    (4,1,'Frate eremita','2000-2001','20 x30 cm.','T.M. e olio su tela/T.M. and oil on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/47_gif.jpg'),
    (4,1,'Trinità dei Monti, in lavorazione','2002','25 x35 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/48_gif.jpg'),
    (4,1,'S. Pietro dal Lungotevere','1999','25 x35 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/49_gif.jpg'),
    (4,1,'P.L. N°5','1994-1995','50x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/5_gif.jpg'),
    (4,1,'Piazza del Popolo all''antica Roma','1998-1999','30x40 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/50_gif.jpg'),
    (4,1,'Piazza del Popolo in bianco e nero','2000-2001','50x70 cm.','Olio e T.M. su tela/Oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/51_gif.jpg'),
    (4,1,'People square as Clown','1999-2000','47x63 cm.','Olio e T.M. su carta/Oil and T.M. on paper','http://www.avant-gardeart.com/perrini/antologica2/images/52_gif.jpg'),
    (4,1,'Madonna 2000-enne, in lavorazione','2000-2001','50x70 cm.','Inchiostro su tela/Ink on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/53_gif.jpg'),
    (4,1,'Iuta abstract','1998-1999','40x50 cm.','Olio, smalto e T.M. su tela di iuta/Oil, varnish and T.M. on iuta canvas','http://www.avant-gardeart.com/perrini/antologica2/images/54_gif.jpg'),
    (4,1,'L''ermafrodita','2000-2001','40x60 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/55_gif.jpg'),
    (4,1,'Piazza del Popolo:notturno','1998-1999','25x35 cm.','Olio, smalto e T.M. su tela/Oil, varnish and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/56_gif.jpg'),
    (4,1,'Marziani','2002','50x60 cm.','Smalto su carta/Varnish on paper','http://www.avant-gardeart.com/perrini/antologica2/images/57_gif.jpg'),
    (4,1,'Genitori','2002','50x60 cm.','Olio. smalto e T.M. su carta/Oil, varnish and T.M. on paper','http://www.avant-gardeart.com/perrini/antologica2/images/58_gif.jpg'),
    (4,1,'Cane da combattimento','2002','47x65 cm.','Olio su carta/Oil on paper','http://www.avant-gardeart.com/perrini/antologica2/images/59_gif.jpg'),
    (4,1,'P.L. N°6','1994-1995','50x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/6_gif.jpg'),
    (4,1,'Santo al ceruleo','2001-2002','40x50 cm.','Olio su tela/Oil on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/60_gif.jpg'),
    (4,1,'Dedicato a Zapata','1996-1997','47x65 cm.','Olio e T.M. su carta/Oil and T.M. on paper','http://www.avant-gardeart.com/perrini/antologica2/images/61_gif.jpg'),
    (4,1,'Il fantasma dell''Indiano','1996-1997','47x65 cm.','Olio e T.M. su carta/Oil and T.M. on paper','http://www.avant-gardeart.com/perrini/antologica2/images/62_gif.jpg'),
    (4,1,'Clown robotico','1996-1997','47x65 cm.','Olio, collage e T.M. su carta/Oil, collage and T.M. on paper','http://www.avant-gardeart.com/perrini/antologica2/images/63_gif.jpg'),
    (4,1,'Bottiglie di liquore','2002','50x60 cm.','Olio su tela/Oil on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/64_gif.jpg'),
    (4,1,'Piazza del Popolo, in bianco e nero, in lavorazione','2001-2002','50x70 cm.','Olio e T.M. su tela/Oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/65_gif.jpg'),
    (4,1,'Madonna 2000-enne','2001-2002','50x70 cm.','Inchiostro su tela/Ink on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/66_gif.jpg'),
    (4,1,'Coliseum','2001-2002','25x35 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/67_gif.jpg'),
    (4,1,'Mobile bar','2002','28x39 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/68_gif.jpg'),
    (4,1,'Notturno a Piazza del Popolo, in lavorazione','2001-2002','25x35 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/69_gif.jpg'),
    (4,1,'P.L. N°7','1994-1995','50x70 cm.','T.M. e polimaterico su carta/T.M. and polimateric on paper','http://www.avant-gardeart.com/perrini/antologica2/images/7_gif.jpg'),
    (4,1,'Trinità dei Monti infiorata','2001-2002','25x35 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/70_gif.jpg'),
    (4,1,'Al Menestrello','2002','50x60 cm.','Olio e T.M. su tela/Oil and T.M. on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/71_gif.jpg'),
    (4,1,'S. Pietro dal Lungotevere','2001-2002','25x35 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/72_gif.jpg'),
    (4,1,'Lametta da barba','2001-2002','25x35 cm.','Olio e smalto su tela/Oil and varnish on canvas','http://www.avant-gardeart.com/perrini/antologica2/images/73_gif.jpg'),
    (4,1,'Alter ego','2002','scultura alta 11 cm.','Ceramica da autocottura/Ceramic as self-cooking','http://www.avant-gardeart.com/perrini/antologica2/images/74_gif.jpg'),
    (4,1,'P.L. N°8','1994-1995','50x70 cm.','T.M. e polimaterico su carta/T.M. and polimateris on paper','http://www.avant-gardeart.com/perrini/antologica2/images/8_gif.jpg'),
    (4,1,'P.L. N°9','1994-1995','50x70 cm.','T.M. e polimaterico su carta/T.M. and polimateris on paper','http://www.avant-gardeart.com/perrini/antologica2/images/9_gif.jpg'),
    (5,1,'M.C.VA N°1/1','2005','27 x 32 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/01_JPG.JPG'),
    (5,1,'S.F.B.NA N°1','2005','27 x 37 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/02_JPG.JPG'),
    (5,1,'G.B.NO N°1','2005','27 x 36 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/03_JPG.JPG'),
    (5,1,'M.D.F.ZZI N°1/1','2005','24 x 28 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/04_JPG.JPG'),
    (5,1,'G.B.NO N°1','2005','27 x 36 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/05_JPG.JPG'),
    (5,1,'S.F.B.NA N°2','2005','27 x 37 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/06_JPG.JPG'),
    (5,1,'M.C.B.NO N°1/2','2005','27 x 33 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/07_JPG.JPG'),
    (5,1,'M.C.B.NO N°1/3','2005','27 x 32 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/08_JPG.JPG'),
    (5,1,'G.B.NO N°3','2005','27 x 36 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/09_JPG.JPG'),
    (5,1,'M.C.B.NO N°2/2','2005','27 x 33 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/10_JPG.JPG'),
    (5,1,'G.B.NO N°4','2005','27 x 36 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/11_JPG.JPG'),
    (5,1,'M.C.B.NO N°2/3','2005','27 x 33 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/12_JPG.JPG'),
    (5,1,'S.F.B.NA N°3','2005','27 x 37 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/13_JPG.JPG'),
    (5,1,'M.C.VA N°2/1','2005','27 x 32 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/14_JPG.JPG'),
    (5,1,'S.F. N°4','2005','27 x 37 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/15_JPG.JPG'),
    (5,1,'G.B.NO N°5','2005','27 x 36 cm.','lastra alluminio-rame lavorata a sbalzo su legno, con stampa e smalto/alluminium-copper plate embossed worked on wood, with print end enamel','http://www.avant-gardeart.com/perrini/icone2005/images/16_JPG.JPG'),
    (6,1,'Piazza del Popolo in Rosa','2004','50 x 70 cm.','smalto e olio su masonite/varnish and oil on pressed paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/01_JPG.JPG'),
    (6,1,'Piazza del Popolo in Blu','2004','50 x 70 cm.','smalto e olio su masonite/varnish and oil on pressed paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/02_JPG.JPG'),
    (6,1,'Piazza del Popolo in Celeste','2004','50 x 70 cm.','smalto e olio su masonite/varnish and oil on pressed paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/03_JPG.JPG'),
    (6,1,'Piazza del Popolo Multicolor','2004','28 x 39 cm.','smalto e olio su tela/varnish and oil on canvas','http://www.avant-gardeart.com/perrini/piazzapopolo/images/04_JPG.JPG'),
    (6,1,'Piazza del Popolo Lercitudo','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/05_JPG.JPG'),
    (6,1,'Piazza del Popolo Ramata','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/06_JPG.JPG'),
    (6,1,'Piazza del Popolo Brennica','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/07_JPG.JPG'),
    (6,1,'Piazza del Popolo Argentea','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/08_JPG.JPG'),
    (6,1,'Piazza del Popolo Ammuffita','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/09_JPG.JPG'),
    (6,1,'Piazza del Popolo Terracquea','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/10_JPG.JPG'),
    (6,1,'Piazza del Popolo Francesique 1','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/11_JPG.JPG'),
    (6,1,'Piazza del Popolo Francesique 2','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/12_JPG.JPG'),
    (6,1,'Piazza del Popolo Cosmica','2004','48 x 66 cm.','smalto e olio su carta/varnish and oil on paper','http://www.avant-gardeart.com/perrini/piazzapopolo/images/13_JPG.JPG'),
    (6,1,'Piazza del Popolo in Arcobaleno','2005','50 x 70 cm.','smalto, olio e gouache su tela/varnish, oil and gouache on canvas','http://www.avant-gardeart.com/perrini/piazzapopolo/images/14_JPG.JPG'),
    (6,1,'Piazza del Popolo in Diamantato','2005','50 x 70 cm.','tecnica mista su tela/mixed technique on canvas','http://www.avant-gardeart.com/perrini/piazzapopolo/images/15_JPG.JPG');
